# Needed for Metal, the hardware acceleration api for osx
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]

# Workaround for https://github.com/conda-forge/librerun-sdk-feedstock/pull/13#issuecomment-2295861606
# Remove once the whole conda-forge switches to clang 17 (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4890)
cxx_compiler_version:      # [osx and arm64]
  - 17                     # [osx and arm64]
c_compiler_version:        # [osx and arm64]
  - 17                     # [osx and arm64]

# Workaround for https://github.com/rerun-io/rerun/issues/7216
# Use the same version specified in https://github.com/rerun-io/rerun/blob/0.18.0/rust-toolchain#L8
rust_compiler_version:
  - 1.76.0
