{% set name = "librerun-sdk" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rerun-io/rerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: f143bc9235588c5c6fd936bdab190d6c4b8d0bc2ca932bc44a3399ba5bc19e43

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - cargo-bundle-licenses
    - {{ compiler('rust') }}
  host:
    - libarrow
  # Ensure that the users always instal the same version if it
  # installs both librerun-sdk (C++) and rerun-sdk (Python)
  run_constrained:
    - rerun-sdk {{ version }}

test:
  commands:
    - test -f ${PREFIX}/include/rerun.hpp  # [unix]
    - test -f ${PREFIX}/lib/librerun_sdk${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\rerun.hpp exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\rerun_sdk.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\rerun_sdk.dll exit 1  # [win]
    - cmake-package-check rerun_sdk --targets rerun_sdk
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://www.rerun.io/
  summary: Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time.
  description: |
    The `librerun-sdk` package provides the C++ API for Rerun, while `rerun-sdk` provides the Python API.
  license: MIT OR Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE-MIT
    - LICENSE-APACHE

  doc_url: https://www.rerun.io/docs
  dev_url: https://github.com/rerun-io/rerun

extra:
  recipe-maintainers:
    - traversaro
    - jleibs
